# ICT Market Structure — Demo
> `strategies/market_structure.py` — Swing detection · BOS · CHoCH · Order Blocks

In [112]:
import sys
sys.path.insert(0, r"F:\Claude Projects\quant_ict_trader")

In [113]:
import importlib
import strategies.market_structure as ms_module
importlib.reload(ms_module)
from strategies.market_structure import MarketStructure, analyse

In [114]:
import sys
sys.path.insert(0, r"E:\Claude Projects\quant_ict_trader")

import yfinance as yf
import pandas as pd
from strategies.market_structure import MarketStructure, analyse

## 1 · Load EURUSD 1H data

In [115]:
raw = yf.download('EURUSD=X', period='60d', interval='1h', auto_adjust=True)

# yfinance returns MultiIndex columns — flatten to single level
df = raw.copy()
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0).str.lower()
else:
    df.columns = df.columns.str.lower()
df.index = pd.to_datetime(df.index)
df = df.dropna()

print(f'Rows: {len(df):,}  |  {df.index[0]} → {df.index[-1]}')
df.tail(3)

[*********************100%***********************]  1 of 1 completed

Rows: 1,408  |  2026-02-04 00:00:00+00:00 → 2026-04-28 07:00:00+00:00

Price                         close      high       low      open  volume
Datetime
2026-04-28 05:00:00+00:00  1.170960  1.171646  1.170960  1.171646       0
2026-04-28 06:00:00+00:00  1.169180  1.171097  1.169180  1.170823       0
2026-04-28 07:00:00+00:00  1.169727  1.170412  1.169044  1.169044       0

## 2 · Run analysis

In [116]:
ms = MarketStructure(df, swing_lookback=5)

print(f'Swing Highs : {len(ms.swing_highs)}')
print(f'Swing Lows  : {len(ms.swing_lows)}')
print(f'BOS/CHoCH   : {len(ms.structure_events)}')
print(f'Order Blocks: {len(ms.order_blocks)}')

Swing Highs : 110
Swing Lows  : 105
BOS/CHoCH   : 55
Order Blocks: 55

## 3 · Interactive chart (last 300 candles)

In [117]:
fig = ms.plot(
    last_n=300,
    title='EURUSD 1H — ICT Market Structure',
    height=820,
    max_events=10,           # show only 10 most recent BOS/CHoCH
    show_mitigated_ob=False, # hide already-visited OBs
)
fig.show()

## 4 · Events summary table

In [118]:
ms.summary().tail(15)

                   timestamp       event     price  broken_level
40 2026-04-06 06:00:00+00:00  CHoCH_bull  1.153669      1.153270
41 2026-04-07 01:00:00+00:00  CHoCH_bear  1.153270      1.153802
42 2026-04-07 17:00:00+00:00  CHoCH_bull  1.158078      1.157809
43 2026-04-08 12:00:00+00:00    BOS_bull  1.171783      1.171097
44 2026-04-10 06:00:00+00:00  CHoCH_bear  1.168770      1.168907
45 2026-04-10 13:00:00+00:00  CHoCH_bull  1.173020      1.172608
46 2026-04-13 13:00:00+00:00    BOS_bull  1.170686      1.170275
47 2026-04-16 02:00:00+00:00    BOS_bull  1.182033      1.181056
48 2026-04-17 08:00:00+00:00    BOS_bull  1.179802      1.179106
49 2026-04-17 19:00:00+00:00  CHoCH_bear  1.177163      1.177718
50 2026-04-21 15:00:00+00:00    BOS_bear  1.175503      1.176055
51 2026-04-22 11:00:00+00:00    BOS_bear  1.173709      1.174122
52 2026-04-23 10:00:00+00:00    BOS_bear  1.168634      1.169591
53 2026-04-24 15:00:00+00:00  CHoCH_bull  1.172058      1.171921
54 2026-04-28 01:00:00+00:00  CHoCH_bear  1.171646      1.172196

## 5 · Order blocks table

In [119]:
ms.order_blocks_df()

,timestamp,kind,high,low,open,close,mitigated,mitigated_at
0,2026-02-05 00:00:00+00:00,bearish,1.180777,1.180359,1.180498,1.180638,True,2026-02-05 01:00:00+00:00
1,2026-02-05 19:00:00+00:00,bearish,1.180080,1.179663,1.179663,1.179802,True,2026-02-05 20:00:00+00:00
2,2026-02-06 11:00:00+00:00,bullish,1.179663,1.178967,1.179523,1.179384,True,2026-02-06 12:00:00+00:00
3,2026-02-06 21:00:00+00:00,bullish,1.182732,1.181754,1.182592,1.182173,True,2026-02-06 22:00:00+00:00
4,2026-02-10 09:00:00+00:00,bearish,1.192321,1.191185,1.191327,1.191753,True,2026-02-10 10:00:00+00:00
5,2026-02-13 02:00:00+00:00,bearish,1.187507,1.186662,1.186944,1.187225,True,2026-02-13 03:00:00+00:00
6,2026-02-16 10:00:00+00:00,bearish,1.187085,1.186662,1.186803,1.187085,True,2026-02-16 11:00:00+00:00
7,2026-02-17 19:00:00+00:00,bullish,1.185396,1.184694,1.185255,1.185115,True,2026-02-17 20:00:00+00:00
8,2026-02-18 15:00:00+00:00,bearish,1.182872,1.181893,1.181893,1.182592,True,2026-02-18 16:00:00+00:00
9,2026-02-19 07:00:00+00:00,bearish,1.180638,1.179663,1.179941,1.180498,True,2026-02-19 08:00:00+00:00
10,2026-02-25 03:00:00+00:00,bullish,1.179663,1.178967,1.179663,1.179384,True,2026-02-25 04:00:00+00:00
11,2026-02-25 22:00:00+00:00,bullish,1.181754,1.180916,1.181614,1.181474,True,2026-02-25 23:00:00+00:00
12,2026-03-02 01:00:00+00:00,bearish,1.179802,1.177856,1.178134,1.179384,True,2026-03-02 02:00:00+00:00
13,2026-03-03 01:00:00+00:00,bearish,1.170960,1.169727,1.169864,1.170001,True,2026-03-03 02:00:00+00:00
14,2026-03-04 08:00:00+00:00,bullish,1.161980,1.160093,1.161980,1.160227,True,2026-03-04 09:00:00+00:00
15,2026-03-06 10:00:00+00:00,bearish,1.158749,1.157675,1.157809,1.158346,True,2026-03-06 11:00:00+00:00
16,2026-03-06 21:00:00+00:00,bearish,1.162250,1.160901,1.160901,1.162115,True,2026-03-06 22:00:00+00:00
17,2026-03-09 12:00:00+00:00,bullish,1.157140,1.155402,1.156470,1.155668,True,2026-03-09 13:00:00+00:00
18,2026-03-10 16:00:00+00:00,bearish,1.165773,1.164280,1.164822,1.165501,True,2026-03-10 17:00:00+00:00
19,2026-03-11 04:00:00+00:00,bearish,1.163873,1.163196,1.163332,1.163738,True,2026-03-11 05:00:00+00:00
20,2026-03-11 21:00:00+00:00,bearish,1.157809,1.157006,1.157006,1.157809,True,2026-03-11 22:00:00+00:00
21,2026-03-12 09:00:00+00:00,bearish,1.156337,1.154868,1.154868,1.156337,True,2026-03-12 10:00:00+00:00
22,2026-03-13 00:00:00+00:00,bearish,1.153136,1.152472,1.152605,1.152738,True,2026-03-13 01:00:00+00:00
23,2026-03-13 17:00:00+00:00,bearish,1.144820,1.143772,1.144427,1.144558,True,2026-03-13 18:00:00+00:00
24,2026-03-16 07:00:00+00:00,bullish,1.143772,1.141944,1.143380,1.142857,True,2026-03-16 08:00:00+00:00
25,2026-03-17 10:00:00+00:00,bullish,1.151808,1.150748,1.151410,1.151013,True,2026-03-17 11:00:00+00:00
26,2026-03-18 17:00:00+00:00,bearish,1.151941,1.150616,1.151543,1.151941,True,2026-03-18 18:00:00+00:00
27,2026-03-19 10:00:00+00:00,bullish,1.148106,1.147052,1.147974,1.147710,True,2026-03-19 11:00:00+00:00
28,2026-03-23 08:00:00+00:00,bearish,1.154868,1.153136,1.153270,1.153403,True,2026-03-23 09:00:00+00:00
29,2026-03-23 10:00:00+00:00,bullish,1.149822,1.148897,1.149690,1.148897,True,2026-03-23 11:00:00+00:00
30,2026-03-24 17:00:00+00:00,bullish,1.158614,1.156337,1.158614,1.157943,True,2026-03-24 18:00:00+00:00
31,2026-03-25 10:00:00+00:00,bearish,1.160766,1.159958,1.160631,1.160766,True,2026-03-25 11:00:00+00:00
32,2026-03-26 06:00:00+00:00,bearish,1.157006,1.155668,1.156203,1.157006,True,2026-03-26 07:00:00+00:00
33,2026-03-26 18:00:00+00:00,bearish,1.153669,1.152871,1.152871,1.153669,True,2026-03-26 19:00:00+00:00
34,2026-03-27 04:00:00+00:00,bearish,1.154601,1.154068,1.154201,1.154601,True,2026-03-27 05:00:00+00:00
35,2026-03-30 09:00:00+00:00,bearish,1.150086,1.148897,1.149822,1.149954,True,2026-03-30 10:00:00+00:00
36,2026-03-31 10:00:00+00:00,bullish,1.147315,1.146132,1.147184,1.146263,True,2026-03-31 11:00:00+00:00
37,2026-04-01 03:00:00+00:00,bullish,1.157140,1.156337,1.157140,1.156470,True,2026-04-01 04:00:00+00:00
38,2026-04-02 00:00:00+00:00,bearish,1.160093,1.159017,1.159286,1.160093,True,2026-04-02 01:00:00+00:00
39,2026-04-03 13:00:00+00:00,bearish,1.154201,1.153136,1.153270,1.153935,True,2026-04-03 14:00:00+00:00
40,2026-04-06 03:00:00+00:00,bullish,1.152605,1.152074,1.152472,1.152206,True,2026-04-06 04:00:00+00:00
41,2026-04-06 21:00:00+00:00,bearish,1.155135,1.154201,1.154468,1.154601,True,2026-04-06 22:00:00+00:00
42,2026-04-07 10:00:00+00:00,bullish,1.156604,1.155135,1.156604,1.155668,True,2026-04-07 11:00:00+00:00
43,2026-04-08 09:00:00+00:00,bullish,1.169180,1.168224,1.168497,1.168361,True,2026-04-08 10:00:00+00:00
44,2026-04-10 03:00:00+00:00,bearish,1.170001,1.169317,1.169454,1.169864,True,2026-04-10 04:00:00+00:00
45,2026-04-10 07:00:00+00:00,bullish,1.169317,1.168224,1.168907,1.168224,True,2026-04-10 08:00:00+00:00
46,2026-04-13 11:00:00+00:00,bullish,1.170275,1.168634,1.169864,1.168634,True,2026-04-13 12:00:00+00:00
47,2026-04-16 01:00:00+00:00,bullish,1.181195,1.180080,1.181056,1.180498,True,2026-04-16 02:00:00+00:00
48,2026-04-17 06:00:00+00:00,bullish,1.178550,1.177718,1.178273,1.177856,True,2026-04-17 07:00:00+00:00
49,2026-04-17 12:00:00+00:00,bearish,1.183852,1.179802,1.179802,1.183712,True,2026-04-17 13:00:00+00:00
50,2026-04-21 13:00:00+00:00,bearish,1.177302,1.176471,1.176471,1.176886,True,2026-04-21 14:00:00+00:00
51,2026-04-22 10:00:00+00:00,bearish,1.175641,1.174950,1.174950,1.175503,True,2026-04-22 11:00:00+00:00
52,2026-04-23 05:00:00+00:00,bearish,1.170960,1.170275,1.170275,1.170960,True,2026-04-23 06:00:00+00:00
53,2026-04-24 14:00:00+00:00,bullish,1.171921,1.170823,1.171097,1.170960,True,2026-04-24 15:00:00+00:00
54,2026-04-27 12:00:00+00:00,bearish,1.175779,1.174398,1.174536,1.174812,True,2026-04-27 13:00:00+00:00

## 6 · 4H chart
Higher-timeframe context for confluence.

In [120]:
raw_4h = yf.download('EURUSD=X', period='120d', interval='4h', auto_adjust=True)
df_4h = raw_4h.copy()
if isinstance(df_4h.columns, pd.MultiIndex):
    df_4h.columns = df_4h.columns.get_level_values(0).str.lower()
else:
    df_4h.columns = df_4h.columns.str.lower()
df_4h.index = pd.to_datetime(df_4h.index)
df_4h = df_4h.dropna()

ms_4h = MarketStructure(df_4h, swing_lookback=5)
ms_4h.plot(
    last_n=200,
    title='EURUSD 4H — ICT Market Structure',
    height=820,
).show()

[*********************100%***********************]  1 of 1 completed

In [121]:
import importlib
import strategies.fvg as fvg_module
importlib.reload(fvg_module)
from strategies.fvg import FairValueGap

fvg = FairValueGap(df, min_gap_pips=2.0)
print(f"Total FVGs : {len(fvg.fvgs)}")
print(f"Unfilled   : {len(fvg.unfilled())}")
fvg.plot(last_n=300, title="EURUSD 1H — Fair Value Gaps").show()

Total FVGs : 259
Unfilled   : 13

In [122]:
import importlib
import strategies.liquidity as liq_module
importlib.reload(liq_module)
from strategies.liquidity import Liquidity

liq = Liquidity(df, swing_lookback=5, equal_threshold=3.0)
print(f"Equal Highs : {len(liq.equal_highs)}")
print(f"Equal Lows  : {len(liq.equal_lows)}")
print(f"Grabs       : {len(liq.grabs)}")
print(f"Active Buy-side  : {len(liq.active_buyside())}")
print(f"Active Sell-side : {len(liq.active_sellside())}")
liq.plot(last_n=300, title="EURUSD 1H — Liquidity").show()

Equal Highs : 28
Equal Lows  : 22
Grabs       : 1158
Active Buy-side  : 9
Active Sell-side : 6

In [123]:
import importlib
import strategies.entry_model as em_module
importlib.reload(em_module)
from strategies.entry_model import EntryModel

# Download 4H data
raw_4h = yf.download('EURUSD=X', period='120d', interval='4h', auto_adjust=True)
df_4h = raw_4h.copy()
if isinstance(df_4h.columns, pd.MultiIndex):
    df_4h.columns = df_4h.columns.get_level_values(0).str.lower()
df_4h.index = pd.to_datetime(df_4h.index)
df_4h = df_4h.dropna()

# Run model
model = EntryModel(
    df_high=df_4h,
    df_low=df,
    instrument="EURUSD",
    account_balance=10000,
    risk_pct=0.01,
    daily_loss_limit=0.03,
    max_drawdown=0.10,
    tp1_rr=1.0,
    tp2_rr=2.0,
    sl_buffer_pips=3.0,
    min_rr=1.5,
)

print(f"Signals found: {len(model.signals)}")
if model.latest_signal():
    print(model.latest_signal())

model.plot(last_n=300).show()

fig = model.plot(last_n=100)
fig.write_html("chart.html")
print("Open chart.html in your browser")
print(model.latest_signal())
print(f"\nTotal signals: {len(model.signals)}")
print(model.signals_df())

# Check what's being detected
print("HTF Trend:", model._get_htf_trend())
print("LTF Trend:", model._get_ltf_trend())
print()
print("Unfilled FVGs:", len(model.fvg.unfilled()))
for f in model.fvg.unfilled():
    size = (f.top - f.bottom) / 0.0001
    print(f"  {f.kind} FVG | size: {size:.1f} pips | top: {f.top:.5f} | bottom: {f.bottom:.5f}")
print()
print("Active OBs:", len([o for o in model.ms_low.order_blocks if not o.mitigated]))
for ob in [o for o in model.ms_low.order_blocks if not o.mitigated]:
    sl_dist = abs(ob.high - ob.low) / 0.0001
    print(f"  {ob.kind} OB | size: {sl_dist:.1f} pips | high: {ob.high:.5f} | low: {ob.low:.5f}")

current = model.df_low["close"].iloc[-1]
print(f"Current price: {current:.5f}")
print(f"\nLast grab: {model.liq.grabs[-1] if model.liq.grabs else 'None'}")
print(f"Active buyside (EQH): {len(model.liq.active_buyside())}")
for eq in model.liq.active_buyside():
    print(f"  EQH at {eq.price:.5f}")

[*********************100%***********************]  1 of 1 completed

Signals found: 7

==================================================
  SHORT EURUSD
==================================================
  Entry  : 1.17130
  SL     : 1.17608  (47.8 pips)
  TP1    : 1.16653  (RR 1.0:1)
  TP2    : 1.16175  (RR 2.0:1)
  Size   : 0.30 lots
  Risk   : $100.00 (1.0%)
  Trend  : BOS_bear on HTF
  Zone   : Bearish FVG
  Confirm: EQH confluence at 1.17578
==================================================

Open chart.html in your browser

==================================================
  SHORT EURUSD
==================================================
  Entry  : 1.17130
  SL     : 1.17608  (47.8 pips)
  TP1    : 1.16653  (RR 1.0:1)
  TP2    : 1.16175  (RR 2.0:1)
  Size   : 0.30 lots
  Risk   : $100.00 (1.0%)
  Trend  : BOS_bear on HTF
  Zone   : Bearish FVG
  Confirm: EQH confluence at 1.17578
==================================================

Total signals: 7
                  timestamp direction    entry       sl      tp1      tp2  \
0 2026-04-28 07:00:00+00:00     short  1.19161  1.17608  1.17608  1.16754
1 2026-04-28 07:00:00+00:00     short  1.19090  1.17608  1.17608  1.16754
2 2026-04-28 07:00:00+00:00     short  1.18231  1.17608  1.17608  1.16754
3 2026-04-28 07:00:00+00:00     short  1.18120  1.17608  1.17608  1.16754
4 2026-04-28 07:00:00+00:00     short  1.18022  1.17608  1.17608  1.17194
5 2026-04-28 07:00:00+00:00     short  1.17385  1.17608  1.17161  1.16754
6 2026-04-28 07:00:00+00:00     short  1.17130  1.17608  1.16653  1.16175

   sl_pips  rr_tp1  rr_tp2  size_lots  risk_$         zone  \
0    155.3     1.0    1.55       0.09   100.0  Bearish FVG
1    148.2     1.0    1.58       0.10   100.0  Bearish FVG
2     62.3     1.0    2.37       0.23   100.0  Bearish FVG
3     51.2     1.0    2.67       0.28   100.0  Bearish FVG
4     41.4     1.0    2.00       0.35   100.0  Bearish FVG
5     22.3     1.0    2.82       0.64   100.0  Bearish FVG
6     47.8     1.0    2.00       0.30   100.0  Bearish FVG

                     confirm            trend
0  EQH confluence at 1.18737  BOS_bear on HTF
1  EQH confluence at 1.18603  BOS_bear on HTF
2  EQH confluence at 1.17800  BOS_bear on HTF
3  EQH confluence at 1.17800  BOS_bear on HTF
4  EQH confluence at 1.17578  BOS_bear on HTF
5  EQH confluence at 1.17578  BOS_bear on HTF
6  EQH confluence at 1.17578  BOS_bear on HTF
HTF Trend: -1
LTF Trend: -1

Unfilled FVGs: 13
  bearish FVG | size: 8.5 pips | top: 1.19204 | bottom: 1.19119
  bearish FVG | size: 2.8 pips | top: 1.19104 | bottom: 1.19076
  bullish FVG | size: 6.5 pips | top: 1.14443 | bottom: 1.14377
  bullish FVG | size: 19.8 pips | top: 1.14929 | bottom: 1.14732
  bullish FVG | size: 10.6 pips | top: 1.15048 | bottom: 1.14943
  bullish FVG | size: 4.0 pips | top: 1.15207 | bottom: 1.15168
  bearish FVG | size: 11.2 pips | top: 1.18287 | bottom: 1.18175
  bearish FVG | size: 8.4 pips | top: 1.18161 | bottom: 1.18078
  bearish FVG | size: 2.8 pips | top: 1.18036 | bottom: 1.18008
  bearish FVG | size: 2.8 pips | top: 1.17398 | bottom: 1.17371
  bearish FVG | size: 2.7 pips | top: 1.17247 | bottom: 1.17220
  bearish FVG | size: 4.1 pips | top: 1.17151 | bottom: 1.17110
  bearish FVG | size: 5.5 pips | top: 1.17096 | bottom: 1.17041

Active OBs: 0
Current price: 1.16973

Last grab: LiquidityGrab(index=1407, timestamp=Timestamp('2026-04-28 07:00:00+0000', tz='UTC'), price=np.float64(1.1690436601638794), kind='bull_grab', swept_level=np.float64(1.1695905923843384))
Active buyside (EQH): 9
  EQH at 1.17578
  EQH at 1.17800
  EQH at 1.17933
  EQH at 1.18371
  EQH at 1.18526
  EQH at 1.18603
  EQH at 1.18737
  EQH at 1.18883
  EQH at 1.19299

In [124]:
import importlib, strategies.entry_model as em
importlib.reload(em)
from strategies.entry_model import EntryModel

model = EntryModel(df_high=df_4h, df_low=df, instrument="EURUSD",
    account_balance=10000, risk_pct=0.01, daily_loss_limit=0.03,
    max_drawdown=0.10, tp1_rr=1.0, tp2_rr=2.0, sl_buffer_pips=3.0, min_rr=1.5)

print(f"Signals: {len(model.signals)}")
print(model._find_entry_zones("short")[:3])

Signals: 7
[(np.float64(1.1916111707687378), 'Bearish FVG', np.float64(1.1760789850234985)), (np.float64(1.1909014582633972), 'Bearish FVG', np.float64(1.1760789850234985)), (np.float64(1.1823129057884216), 'Bearish FVG', np.float64(1.1760789850234985))]

In [127]:
from utils.signal_viewer import plot_all_signals

plot_all_signals(
    df=df,
    signals=model.signals,
    candles_before=60,
    candles_after=20,
    save_html=r"F:\Claude Projects\quant_ict_trader\signals.html"
)

UnicodeEncodeError: 'charmap' codec can't encode character '\u95f0' in position 4786571: character maps to <undefined>